# -*- coding: utf-8 -*-
"""baselinemodel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lCaHTIxw0dXAF7d-1rukTx9oHac1CbHS
"""

# !pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

from fastbook import *
from fastai.text.all import *
import pandas as pd

df = pd.read_csv('gdrive/MyDrive/germanyPPRs.csv', error_bad_lines=False, engine="python")

dls = TextDataLoaders.from_df(df, text_col = 'text', label_col = 'label')

learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy) # train model
learn.fine_tune(4, 1e-2)


learn.predict('Ausländer haben in diesem Land nichts verloren! Die erneuten Übergriffe durch Migranten zeigen, dass die Intergrationspolitik der Bundesregierung gescheitert ist. Multikulti ist am Ende. Deshalb: Abschiebung jetzt!') 
# this predicts union atm, not so convincing i think